steps:
  # Step 1: Build the custom Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/medflex-plus'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/medflex-plus'

  # Step 2: Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--image-url=gcr.io/$PROJECT_ID/medflex-plus:latest'